/**
 ** Ibrahim Shahid
 * Date: 12/21/2024
 * North Carolina Virtual Public Schools
 * Description: Coin Flipping Algo
 * Difficulties:  I had some struggles doing object oriented programming and stuff so i uesd the ThinkJava2e textbook to help me
 * 
 */
public class Coin { // coin class with private instance variables, constructor, setters and getters, and a flip method

    private String side; // private instance variable to store the coin side status (heads or tails), its a string for simplicity, heads or tails

    // Constructorrr
    public Coin() {
 // when a new coin object is made, we can flip it immediatley 
        flip(); 
    } 

    // Getter for side of the coin
    public String getSide() {
        return side;
    }

   
    public void setSide(String side) { // setter for side
        this.side = side;
    }

    // flip method!
    public void flip() {
        if (Math.random() < 0.5) { // if the random number generated by math.random is less than .5, then flip the side to heads, if not, then give side a value of tails
            side = "heads";
        } else {
            side = "tails";
        }
    }
}
